# Generated by Django 3.0.5 on 2021-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=256)),
                ('expirence', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('job_desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
