# Generated by Django 3.0.5 on 2021-04-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=256)),
                ('job_desc', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=256)),
                ('expirence', models.IntegerField()),
                ('skill', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
            ],
        ),
    ]
