# Generated by Django 3.0.5 on 2021-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210505_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
